### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by KorneliaBastin** [yumeng5/LOTClass#14]
Hi, I am running my code on mac which does not have CUDA and I run into some issues because of that. Any idea how I can resolve it?

Contructing category vocabulary.
Traceback (most recent call last):
  File "src/train.py", line 66, in <module>
    main()
  File "src/train.py", line 55, in main
    trainer.category_vocabulary(top_pred_num=args.top_pred_num, category_vocab_size=args.category_vocab_size)
  File "/Users/user/Downloads/LOTClass-master/src/trainer.py", line 295, in category_vocabulary
    mp.spawn(self.category_vocabulary_dist, nprocs=self.world_size, args=(top_pred_num, loader_name))
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/Users/user/Downloads/LOTClass-master/src/trainer.py", line 259, in category_vocabulary_dist
    model = self.set_up_dist(rank)
  File "/Users/user/Downloads/LOTClass-master/src/trainer.py", line 69, in set_up_dist
    model = self.model.to(rank)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 443, in to
    return self._apply(convert)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 441, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 149, in _lazy_init
    _check_driver()
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 47, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by yumeng5** [comment]
Hi @KorneliaBastin ,

Even though it's possible to modify the PyTorch code to make it executable on CPUs (by removing the distributed training code), training BERT-like models usually is infeasible without GPUs (it will be extremely slow) so it may not really help to adapt the code to run on your mac. My suggestion would be to run the code using GPUs (like Google Colab). 

Thanks,
Yu

**Comment by KorneliaBastin** [comment]
Dear @yumeng5,

I have not thought about google colab but that seems like a great alternative so thank you for the advice! Are there any changes that should be done to the code prior to that or will it be ok to run it exactly the same as per your instructions in the README file?

**Comment by yumeng5** [comment]
Hi @KorneliaBastin ,

I believe you won't need to change the code (other than setting up dependencies, data directories, etc. according to Colab environments). Feel free to let me know if you encounter any issues.

Best,
Yu
