### ISSUE TITLE
Error running with test set

### ISSUE THREAD

**Issue by homahm** [yumeng5/LOTClass#19]
Hi! I receive the following error when try this code for a sample data with 20 class labels. It works with 4 class labels though! can you help me what can be the problem?

Start self-training.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/TVEyesResearch/Codes/LOTClass/src/train.py", line 66, in <module>
    main()
  File "/content/gdrive/MyDrive/TVEyesResearch/Codes/LOTClass/src/train.py", line 59, in main
    trainer.self_train(epochs=args.self_train_epochs, loader_name=args.final_model)
  File "/content/gdrive/.shortcut-targets-by-id/1RpJyUMfb0726y9lCj2gYMZpFOy1sWZdr/TVEyesResearch/Codes/LOTClass/src/trainer.py", line 566, in self_train
    mp.spawn(self.self_train_dist, nprocs=self.world_size, args=(epochs, loader_name))
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/content/gdrive/.shortcut-targets-by-id/1RpJyUMfb0726y9lCj2gYMZpFOy1sWZdr/TVEyesResearch/Codes/LOTClass/src/trainer.py", line 532, in self_train_dist
    test_dataset_loader = self.make_dataloader(rank, self.test_data, self.eval_batch_size) if self.with_test_label else None
  File "/content/gdrive/.shortcut-targets-by-id/1RpJyUMfb0726y9lCj2gYMZpFOy1sWZdr/TVEyesResearch/Codes/LOTClass/src/trainer.py", line 223, in make_dataloader
    dataset = TensorDataset(data_dict["input_ids"], data_dict["attention_masks"], data_dict["labels"])
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py", line 158, in __init__
    assert all(tensors[0].size(0) == tensor.size(0) for tensor in tensors)
AssertionError

**Comment by yumeng5** [comment]
Hi @homahm 

It seems to me that your "input_ids", "attention_masks", and "labels" for the test dataset are not of the same length. Perhaps you could try to print out their lengths after reading the test set (e.g., after the following line of code:)
https://github.com/yumeng5/LOTClass/blob/b914c612c58c35204218bc794e0997a07e9c4842/src/trainer.py#L201

Thanks,
Yu

**Comment by homahm** [comment]
Thanks! The size is correct. This error only happens when I try to scale it to 500K documents for training and a smaller set for test. On smaller set it works.

**Comment by yumeng5** [comment]
Hi @homahm 

I don't think the size of the dataset causes the issue because in the original paper we successfully run on the Amazon dataset with 3M training documents and 400K test documents. I don't have specific ideas about what could have caused the issue (if it's not about the tensor sizes being different) only based on the error log, so I'm afraid I could not provide further help.

Best,
Yu
