### ISSUE TITLE
EnvironmentError when running code

### ISSUE THREAD

**Issue by jamestch** [yumeng5/LOTClass#7]
certifi       2020.12.5
chardet       4.0.0
click         7.1.2
dataclasses   0.8
filelock      3.0.12
future        0.18.2
idna          2.10
joblib        1.0.0
nltk          3.5
numpy         1.19.5
packaging     20.8
pip           21.0
pyparsing     2.4.7
regex         2020.11.13
requests      2.25.1
sacremoses    0.0.43
sentencepiece 0.1.95
setuptools    36.4.0
six           1.15.0
tokenizers    0.8.1rc2
torch         1.5.0
tqdm          4.56.0
transformers  3.3.1
urllib3       1.26.3
wheel         0.29.0

Run ''sh agnews.sh", get the following errors,Could you help check it?
Namespace(accum_steps=4, category_vocab_size=100, dataset_dir='datasets/agnews/', dist_port=12345, early_stop=False, eval_batch_size=128, final_model='final_model.pt', gpus=1, label_names_file='label_names.txt', match_threshold=20, max_len=200, mcp_epochs=3, out_file='out.txt', self_train_epochs=1.0, test_file='test.txt', test_label_file='test_labels.txt', top_pred_num=50, train_batch_size=32, train_file='train.txt', update_interval=50)
Effective training batch size: 128
Downloading: 100%|###########################################################################################################################################################| 232k/232k [13:44<00:00, 281B/s]
Label names used for each class are: {0: ['politics'], 1: ['sports'], 2: ['business'], 3: ['technology']}
Traceback (most recent call last):
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/transformers/configuration_utils.py", line 359, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/train.py", line 66, in <module>
    main()
  File "src/train.py", line 53, in main
    trainer = LOTClassTrainer(args)
  File "/root/app/LOTClass/src/trainer.py", line 51, in __init__
    num_labels=self.num_class)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/transformers/modeling_utils.py", line 854, in from_pretrained
    **kwargs,
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/transformers/configuration_utils.py", line 315, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/transformers/configuration_utils.py", line 368, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-uncased' is the correct path to a directory containing a config.json file

**Comment by jamestch** [comment]
I had solved the problem by run the code below：
`from transformers import BertForMaskedLM
model = BertForMaskedLM.from_pretrained("bert-base-cased")`
this link helps me [https://github.com/huggingface/transformers/issues/2110](https://github.com/huggingface/transformers/issues/2110)
